#!/usr/bin/env python
"""Stage 2 of the receptor cross-solver check: FV ↔ FEniCSx joint refinement for the three-region
membrane-coupled MOL integrator (`integrate_membrane_coupled`).

Reads the lowered geometry+math (`receptor_{geom,math}.yaml`) and the FV reference fields generated by
`receptor_fv.py`, then runs the **whole imported pipeline** — `import_geometry` + `import_math_description`
(the membrane reaction trace-wrapped, the jump conditions → `interface_flux`, VCell's `KFlux·KMOLE` unit
factors carried as parameters) → `normalize_to_geometry_frame` → `realize_interface_coupled` →
`integrate_membrane_coupled` — and compares the depleted ligand fields `s_cyto` / `s_ext` to FV on the FV
grid, under joint mesh refinement. Both solvers solve VCell's identical math at ≈0 time error (FV is
Sundials/CVODE, ours is PETSc TS BDF), so the residual is the spatial (membrane) discretization, which
shrinks ~first order with the body-fitted membrane.

    ../pyvcell/.venv/bin/python cross_validation/receptor_fv.py            # stage 1 (FV, pyvcell env)
    .pixi/envs/dev/bin/python   cross_validation/receptor_convergence.py   # stage 2 (this, dev env)
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pyvcell.vcml.models_geometry as gmod
import pyvcell.vcml.models_math as mmod
import yaml
from compare_fenics_vs_fv import _eval_on_grid

from vcell_fenics.backend import integrate_membrane_coupled
from vcell_fenics.backend.realize import realize_interface_coupled
from vcell_fenics.pyvcell_bridge import import_geometry, import_math_description, normalize_to_geometry_frame

_CV = Path(__file__).resolve().parent
_RESOLUTIONS = (64, 128, 256)
_T = 2.0  # mid-transient: both ligands clearly depleted (s_cyto ≈ 0.77, s_ext ≈ 0.94), not yet saturated


def main() -> None:
    geo = gmod.Geometry.model_validate(yaml.safe_load((_CV / "receptor_geom.yaml").read_text()))
    math_raw = mmod.MathDescription.model_validate(yaml.safe_load((_CV / "receptor_math.yaml").read_text()))
    geometry_desc = import_geometry(geo)
    math_desc = import_math_description(math_raw, geometry=geometry_desc.name, dim=2)

    print(f"=== receptor binding: FV ↔ FEniCSx joint refinement, t={_T} ===")
    print(f"{'N':>5} {'h':>9} {'relL2(FEM,FV)':>14} {'ratio':>7}  (s_cyto in disk, s_ext outside)")
    previous = None
    for n in _RESOLUTIONS:
        ref = np.load(_CV / f"receptor_fv_{n}.npz")
        x, y, radius = ref["x"], ref["y"], float(ref["radius"])
        ti = int(np.argmin(np.abs(ref["t"] - _T)))
        grid_x, grid_y = np.meshgrid(x, y, indexing="xy")
        r2 = grid_x**2 + grid_y**2
        in_disk = r2 < (0.9 * radius) ** 2  # interior of the cytosol (skip the membrane band)
        in_ext = r2 > (1.1 * radius) ** 2  # interior of the extracellular

        gd, md = normalize_to_geometry_frame(geometry_desc, math_desc)
        geometry = realize_interface_coupled(
            gd,
            inner_subdomain="cyto_dom",
            outer_subdomain="ext_dom",
            membrane_subdomain="mem_dom",
            interface="mem_dom",
            h=2.0 / n,
        )
        result = integrate_membrane_coupled(md, geometry, t_final=_T)
        ours_cyto = _eval_on_grid(result.field("s_cyto"), geometry.inner_mesh, x, y)
        ours_ext = _eval_on_grid(result.field("s_ext"), geometry.outer_mesh, x, y)

        err2 = np.nansum((ours_cyto[in_disk] - ref["s_cyto"][ti][in_disk]) ** 2)
        err2 += np.nansum((ours_ext[in_ext] - ref["s_ext"][ti][in_ext]) ** 2)
        ref2 = np.nansum(ref["s_cyto"][ti][in_disk] ** 2) + np.nansum(ref["s_ext"][ti][in_ext] ** 2)
        rel = float(np.sqrt(err2 / ref2))
        print(f"{n:5d} {2.0 / n:9.4f} {rel:14.4%} {'' if previous is None else f'{previous / rel:.2f}x'}")
        previous = rel


if __name__ == "__main__":
    main()
