"""Self-organizing chemotaxis: a cell migrates up an external ligand gradient.

This is the migrating-cell North Star, end to end, built entirely from the membrane-coupled solver
(`assemble_membrane_coupled`) and the force-balance mesh motion (`ForceBalanceMeshMotion`). The ONLY
asymmetry put in is an external extracellular ligand gradient; everything downstream self-organizes:

    ligand gradient  →  asymmetric binding  →  receptor (R) polarization  →  asymmetric membrane tension
                                                                                        ↓
                              cell migrates up-gradient  ←  surface-tension force balance (Stokes)

The receptor density is initially uniform (zero); its polarity is *emergent*, generated by binding more
ligand on the high-concentration side, not prescribed. The membrane tension is coupled to R
(`γ = base + sensitivity·R`), so the polarized receptor makes the membrane contract harder on the
ligand-rich side and the cell translates toward it. Total ligand (free + bound) is conserved throughout.

Run (in the dev env):

    .pixi/envs/dev/bin/python examples/self_organizing_chemotaxis.py
"""

from __future__ import annotations

import numpy as np

from vcell_fenics.backend.geometry import make_two_bulk_membrane_geometry
from vcell_fenics.backend.interface_coupled import ForceBalanceMeshMotion, assemble_membrane_coupled
from vcell_fenics.formalism.schema import (
    BCInterfaceFlux,
    MathDescription,
    ParameterConstant,
    Subdomain,
    TemplateEquation,
    Variable,
)

# --- model: a receptor binding ligand from both compartments, ligand richer on the +x side ------------
KON, RMAX, SENSITIVITY, BASE_TENSION, DT, STEPS = 0.8, 3.0, 0.5, 0.5, 0.02, 60
LIGAND_GRADIENT = "0.6 + 0.6 * geom.x[0]"  # extracellular ligand: low at x=−0.5, high at x=+0.5


def model() -> MathDescription:
    return MathDescription(
        geometry="cell",
        subdomains=[
            Subdomain(name="cyto", kind="volume"),
            Subdomain(name="ext", kind="volume"),
            Subdomain(name="pm", kind="surface"),
        ],
        variables=[
            Variable(name="L_in", subdomain="cyto"),
            Variable(name="L_out", subdomain="ext"),
            Variable(name="R", subdomain="pm"),
        ],
        parameters=[ParameterConstant(name="kon", value=KON), ParameterConstant(name="Rmax", value=RMAX)],
        equations=[
            TemplateEquation(
                template="bulk_radv_diff",
                variable="L_in",
                subdomain="cyto",
                temporality="time_dependent",
                terms={"diffusion": "1.0"},
                initial_condition="0.0",
            ),
            TemplateEquation(
                template="bulk_radv_diff",
                variable="L_out",
                subdomain="ext",
                temporality="time_dependent",
                terms={"diffusion": "0.3"},
                initial_condition=LIGAND_GRADIENT,
            ),
            TemplateEquation(
                template="surface_pde_with_dilution",
                variable="R",
                subdomain="pm",
                temporality="time_dependent",
                terms={"diffusion": "0.02", "source": "kon * (trace(L_in) + trace(L_out)) * (Rmax - R)"},
                initial_condition="0.0",  # uniform — the polarity is emergent, not prescribed
            ),
        ],
        boundary_conditions=[
            BCInterfaceFlux(variable="L_in", boundary="pm", expression="-kon * trace(L_in) * (Rmax - R)"),
            BCInterfaceFlux(variable="L_out", boundary="pm", expression="-kon * trace(L_out) * (Rmax - R)"),
        ],
    )


def centroid(geom) -> np.ndarray:  # type: ignore[no-untyped-def]
    x = geom.membrane_mesh.geometry.x
    return np.array([x[:, 0].mean(), x[:, 1].mean()])


def receptor_polarity(problem) -> float:  # type: ignore[no-untyped-def]
    field = problem.field("R")
    xc = field.function_space.tabulate_dof_coordinates()[:, 0]
    r = field.x.array
    return float(r[xc > 0].mean() - r[xc < 0].mean())


def main() -> None:
    geom = make_two_bulk_membrane_geometry(
        "cell",
        inner="cyto",
        outer_subdomain="ext",
        membrane="pm",
        interface="pm",
        outer="wall",
        inner_radius=0.5,
        outer_radius=1.0,
        h=0.05,
    )
    motion = ForceBalanceMeshMotion(geom, tension=BASE_TENSION, dt=DT)
    problem = assemble_membrane_coupled(model(), geom, dt=DT, motion=motion)
    total0, start = problem.total_mass(), centroid(geom)

    print(f"  ligand gradient: {LIGAND_GRADIENT}   tension γ = {BASE_TENSION} + {SENSITIVITY}·R")
    print(f"\n  {'t':>5} {'R polarity (+x−−x)':>20} {'centroid x':>12} {'bound R':>9} {'mass drift':>12}")
    for step in range(STEPS):
        problem.step()
        # close the mechano-chemical loop: tension follows the freshly-solved receptor density
        motion.update_tension_from_receptor(problem.field("R"), base=BASE_TENSION, sensitivity=SENSITIVITY)
        if step % 10 == 9 or step == 0:
            cx = centroid(geom)[0] - start[0]
            print(
                f"  {(step + 1) * DT:5.2f} {receptor_polarity(problem):>20.4f} {cx:>+12.4f} "
                f"{problem.mass('R'):>9.3f} {problem.total_mass() / total0 - 1.0:>+12.2e}"
            )

    shift = centroid(geom) - start
    print(f"\n  net migration: Δx = {shift[0]:+.4f}, Δy = {shift[1]:+.4f}  (up the gradient, toward +x)")
    print("  the receptor polarity, the tension asymmetry, and the motion all self-organized from the")
    print("  ligand gradient alone — and total ligand was conserved to round-off throughout.")


if __name__ == "__main__":
    main()
