"""Minimal local stub for the netgen.csg subset vcell-fenics uses — the analytic CSG
box whose surface seeds 3D multi-region volume meshing (backend/realize)."""

from netgen.meshing import Mesh

class Pnt:
    def __init__(self, x: float, y: float, z: float) -> None: ...

class Solid:
    def mat(self, name: str) -> Solid: ...
    def __add__(self, other: Solid) -> Solid: ...
    def __sub__(self, other: Solid) -> Solid: ...

class OrthoBrick(Solid):
    def __init__(self, p1: Pnt, p2: Pnt) -> None: ...

class Sphere(Solid):
    def __init__(self, center: Pnt, radius: float) -> None: ...

class CSGeometry:
    def __init__(self) -> None: ...
    def Add(self, solid: Solid) -> int: ...
    def GenerateMesh(self, *, maxh: float) -> Mesh: ...
